/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.google.template.soy.exprparse;

public interface ExpressionParserConstants {

  int EOF = 0;
  int NULL = 1;
  int BOOLEAN = 2;
  int INTEGER = 3;
  int FLOAT = 4;
  int STRING = 5;
  int DEC_DIGITS = 6;
  int HEX_DIGIT = 7;
  int UNARY_OR_BINARY_OP = 8;
  int ONLY_UNARY_OP = 9;
  int ONLY_BINARY_OP = 10;
  int IDENT = 11;
  int DOLLAR_IDENT = 12;
  int DOT_IDENT = 13;
  int DOT_INDEX = 14;
  int WS = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"null\"",
    "<BOOLEAN>",
    "<INTEGER>",
    "<FLOAT>",
    "<STRING>",
    "<DEC_DIGITS>",
    "<HEX_DIGIT>",
    "\"-\"",
    "\"not\"",
    "<ONLY_BINARY_OP>",
    "<IDENT>",
    "<DOLLAR_IDENT>",
    "<DOT_IDENT>",
    "<DOT_INDEX>",
    "<WS>",
    "\",\"",
    "\"?\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"$ij.\"",
  };

}
