/* Generated By:JavaCC: Do not edit this line. SoyFileParserConstants.java */
package com.google.template.soy.soyparse;

public interface SoyFileParserConstants {

  int EOF = 0;
  int DELPACKAGE_TAG = 1;
  int XXX_DELPACKAGE_TAG_NOT_SOL = 2;
  int XXX_DELPACKAGE_TAG_NOT_EOL = 3;
  int XXX_DELPACKAGE_INVALID = 4;
  int NAMESPACE_TAG = 5;
  int XXX_NAMESPACE_TAG_NOT_SOL = 6;
  int XXX_NAMESPACE_TAG_NOT_EOL = 7;
  int XXX_NAMESPACE_INVALID = 8;
  int SOY_DOC_START = 9;
  int SOY_DOC_NEWLINE = 10;
  int SOY_DOC_CHAR = 11;
  int SOY_DOC_END = 12;
  int XXX_SOY_DOC_START_NOT_SOL = 13;
  int XXX_SOY_DOC_END_NOT_EOL = 14;
  int ANY_TEMPLATE_TAG = 15;
  int TEMPLATE_BODY_CHAR = 16;
  int TEMPLATE_BODY = 17;
  int XXX_TEMPLATE_TAG_NOT_SOL = 18;
  int XXX_TEMPLATE_TAG_NOT_EOL = 19;
  int XXX_END_TEMPLATE_TAG_NOT_SOL = 20;
  int XXX_END_TEMPLATE_TAG_NOT_EOL = 21;
  int XXX_TEMPLATE_TAG_INVALID = 22;
  int XXX_END_TEMPLATE_TAG_INVALID = 23;
  int ANY_TEMPLATE_CMD_NAME = 24;
  int SKIPPED_NEWLINE = 25;
  int SKIPPED_CHAR = 26;
  int ANY_CHAR = 27;
  int WS = 28;
  int NEWLINE = 29;
  int WS_UNTIL_EOL = 30;
  int NOT_SOL = 31;
  int NOT_EOL = 32;
  int NOT_BRACE = 33;
  int IDENT = 34;
  int DOTTED_IDENT = 35;

  int DEFAULT = 0;
  int IN_TEMPLATE = 1;
  int IN_SOY_DOC = 2;

  String[] tokenImage = {
    "<EOF>",
    "<DELPACKAGE_TAG>",
    "<XXX_DELPACKAGE_TAG_NOT_SOL>",
    "<XXX_DELPACKAGE_TAG_NOT_EOL>",
    "\"{delpackage\"",
    "<NAMESPACE_TAG>",
    "<XXX_NAMESPACE_TAG_NOT_SOL>",
    "<XXX_NAMESPACE_TAG_NOT_EOL>",
    "\"{namespace\"",
    "\"/**\"",
    "<SOY_DOC_NEWLINE>",
    "<SOY_DOC_CHAR>",
    "<SOY_DOC_END>",
    "<XXX_SOY_DOC_START_NOT_SOL>",
    "<XXX_SOY_DOC_END_NOT_EOL>",
    "<ANY_TEMPLATE_TAG>",
    "<TEMPLATE_BODY_CHAR>",
    "<TEMPLATE_BODY>",
    "<XXX_TEMPLATE_TAG_NOT_SOL>",
    "<XXX_TEMPLATE_TAG_NOT_EOL>",
    "<XXX_END_TEMPLATE_TAG_NOT_SOL>",
    "<XXX_END_TEMPLATE_TAG_NOT_EOL>",
    "<XXX_TEMPLATE_TAG_INVALID>",
    "<XXX_END_TEMPLATE_TAG_INVALID>",
    "<ANY_TEMPLATE_CMD_NAME>",
    "<SKIPPED_NEWLINE>",
    "<SKIPPED_CHAR>",
    "<ANY_CHAR>",
    "<WS>",
    "<NEWLINE>",
    "<WS_UNTIL_EOL>",
    "<NOT_SOL>",
    "<NOT_EOL>",
    "<NOT_BRACE>",
    "<IDENT>",
    "<DOTTED_IDENT>",
  };

}
