/* Generated By:JavaCC: Do not edit this line. TemplateParserConstants.java */
package com.google.template.soy.soyparse;

public interface TemplateParserConstants {

  int EOF = 0;
  int LINE_COMMENT = 1;
  int BLOCK_COMMENT_START = 2;
  int BLOCK_COMMENT_END = 3;
  int BLOCK_COMMENT_CHAR = 4;
  int SOY_TAG_OPEN_1 = 5;
  int SOY_TAG_OPEN_2 = 6;
  int XXX_UNMATCHED_RIGHT_BRACE_1 = 7;
  int XXX_UNMATCHED_RIGHT_BRACE_2 = 8;
  int CMD_NAME_SP = 9;
  int CMD_NAME_NIL = 10;
  int CMD_NAME_LF = 11;
  int CMD_NAME_CR = 12;
  int CMD_NAME_TAB = 13;
  int CMD_NAME_LB = 14;
  int CMD_NAME_RB = 15;
  int CMD_NAME_LITERAL = 16;
  int CMD_NAME_END_LITERAL = 17;
  int CMD_NAME_MSG = 18;
  int CMD_NAME_END_MSG = 19;
  int CMD_NAME_PLURAL = 20;
  int CMD_NAME_END_PLURAL = 21;
  int CMD_NAME_SELECT = 22;
  int CMD_NAME_END_SELECT = 23;
  int CMD_NAME_PRINT = 24;
  int CMD_NAME_CSS = 25;
  int CMD_NAME_LET = 26;
  int CMD_NAME_END_LET = 27;
  int CMD_NAME_IF = 28;
  int CMD_NAME_ELSEIF = 29;
  int CMD_NAME_ELSE = 30;
  int CMD_NAME_END_IF = 31;
  int CMD_NAME_SWITCH = 32;
  int CMD_NAME_END_SWITCH = 33;
  int CMD_NAME_FOREACH = 34;
  int CMD_NAME_IFEMPTY = 35;
  int CMD_NAME_END_FOREACH = 36;
  int CMD_NAME_FOR = 37;
  int CMD_NAME_END_FOR = 38;
  int CMD_NAME_ANY_CALL = 39;
  int CMD_NAME_END_ANY_CALL = 40;
  int CMD_NAME_PARAM = 41;
  int CMD_NAME_END_PARAM = 42;
  int CMD_NAME_CASE = 43;
  int CMD_NAME_DEFAULT = 44;
  int CMD_NAME_NAMESPACE = 45;
  int CMD_NAME_TEMPLATE = 46;
  int CMD_NAME_END_TEMPLATE = 47;
  int XXX_NO_CMD_NAME = 48;
  int XXX_BRACE_AFTER_SOY_TAG_OPEN = 49;
  int REG_SOY_TAG_CLOSE_AFTER_CMD_NAME_1 = 50;
  int SELF_ENDING_SOY_TAG_CLOSE_AFTER_CMD_NAME_1 = 51;
  int REG_SOY_TAG_CLOSE_AFTER_CMD_NAME_2 = 52;
  int SELF_ENDING_SOY_TAG_CLOSE_AFTER_CMD_NAME_2 = 53;
  int WS_AFTER_CMD_NAME = 54;
  int NOT_CMD_NAME_BOUNDARY_AFTER_CMD_NAME = 55;
  int CMD_TEXT_DIRECTIVE_NAME = 56;
  int CMD_TEXT_PHNAME_ATTR = 57;
  int XXX_CMD_TEXT_PHNAME_NOT_IDENT = 58;
  int CMD_TEXT_CHAR_1 = 59;
  int CMD_TEXT_CHAR_2 = 60;
  int REG_SOY_TAG_CLOSE_AFTER_CMD_TEXT_1 = 61;
  int SELF_ENDING_SOY_TAG_CLOSE_AFTER_CMD_TEXT_1 = 62;
  int REG_SOY_TAG_CLOSE_AFTER_CMD_TEXT_2 = 63;
  int SELF_ENDING_SOY_TAG_CLOSE_AFTER_CMD_TEXT_2 = 64;
  int XXX_LEFT_BRACE_IN_SOY_TAG_1 = 65;
  int XXX_DOUBLE_RIGHT_BRACE_IN_SOY_TAG_1 = 66;
  int XXX_DOUBLE_LEFT_BRACE_IN_SOY_TAG_2 = 67;
  int XXX_BRACE_BEFORE_SOY_TAG_CLOSE = 68;
  int MSG_HTML_TAG_OPEN = 69;
  int MSG_HTML_TAG_CLOSE = 70;
  int LITERAL_RAW_TEXT_CONTENT = 72;
  int XXX_INVALID_END_LITERAL_TAG = 73;
  int XXX_NESTED_LITERAL_TAG = 74;
  int BASIC_RAW_TEXT_CHAR = 75;
  int ANY_CHAR = 76;
  int WS = 77;
  int WS_CHAR = 78;
  int NOT_WS = 79;
  int BRACE = 80;
  int NOT_BRACE = 81;
  int IDENT = 82;

  int DEFAULT = 0;
  int DEFAULT_IN_MSG_BLOCK = 1;
  int IN_COMMENT_BLOCK = 2;
  int AFTER_SOY_TAG_OPEN = 3;
  int AFTER_CMD_NAME_1 = 4;
  int AFTER_CMD_NAME_2 = 5;
  int IN_CMD_TEXT_1 = 6;
  int IN_CMD_TEXT_2 = 7;
  int IN_LITERAL_BLOCK = 8;

  String[] tokenImage = {
    "<EOF>",
    "<LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<BLOCK_COMMENT_CHAR>",
    "\"{\"",
    "\"{{\"",
    "\"}\"",
    "\"}}\"",
    "\"sp\"",
    "\"nil\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "\"lb\"",
    "\"rb\"",
    "\"literal\"",
    "\"/literal\"",
    "\"msg\"",
    "\"/msg\"",
    "\"plural\"",
    "\"/plural\"",
    "\"select\"",
    "\"/select\"",
    "\"print\"",
    "\"css\"",
    "\"let\"",
    "\"/let\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"/if\"",
    "\"switch\"",
    "\"/switch\"",
    "\"foreach\"",
    "\"ifempty\"",
    "\"/foreach\"",
    "\"for\"",
    "\"/for\"",
    "<CMD_NAME_ANY_CALL>",
    "<CMD_NAME_END_ANY_CALL>",
    "\"param\"",
    "\"/param\"",
    "\"case\"",
    "\"default\"",
    "\"namespace\"",
    "\"template\"",
    "\"/template\"",
    "\"\"",
    "<XXX_BRACE_AFTER_SOY_TAG_OPEN>",
    "\"}\"",
    "\"/}\"",
    "\"}}\"",
    "\"/}}\"",
    "<WS_AFTER_CMD_NAME>",
    "\"\"",
    "<CMD_TEXT_DIRECTIVE_NAME>",
    "<CMD_TEXT_PHNAME_ATTR>",
    "<XXX_CMD_TEXT_PHNAME_NOT_IDENT>",
    "<CMD_TEXT_CHAR_1>",
    "<CMD_TEXT_CHAR_2>",
    "\"}\"",
    "\"/}\"",
    "\"}}\"",
    "\"/}}\"",
    "\"{\"",
    "<XXX_DOUBLE_RIGHT_BRACE_IN_SOY_TAG_1>",
    "\"{{\"",
    "<XXX_BRACE_BEFORE_SOY_TAG_CLOSE>",
    "\"<\"",
    "\">\"",
    "<token of kind 71>",
    "<LITERAL_RAW_TEXT_CONTENT>",
    "<XXX_INVALID_END_LITERAL_TAG>",
    "<XXX_NESTED_LITERAL_TAG>",
    "<BASIC_RAW_TEXT_CHAR>",
    "<ANY_CHAR>",
    "<WS>",
    "<WS_CHAR>",
    "<NOT_WS>",
    "<BRACE>",
    "<NOT_BRACE>",
    "<IDENT>",
  };

}
